### ISSUE TITLE
Verification stats in docs

### ISSUE THREAD

**Issue by adamant-pwn** [online-judge-tools/verification-helper#434]
## Description / 説明

Is it possible to include verification stats in the generated docs (time/memory consumption)?

## Motivation / 動機

It would be very nice to have some indication of how particular library performs without running the verification locally or submitting to Library Judge.

## Other notes / その他

-   Will you try to create a pull request?
    -   no

**Comment by kzrnm** [comment]
In my opinion, it would be very difficult because `.verify-helper/timestamps.remote.json` does not retain the results of the previous run.
[competitive-verifier](https://competitive-verifier.github.io/competitive-verifier/installer.html), which is my fork with much rewritten code, can display verification stats.

![image](https://github.com/online-judge-tools/verification-helper/assets/32071278/3f0ed4d6-d3e0-4076-ba1f-128998883320)

**Comment by adamant-pwn** [comment]
Wow, competitive-verifier is an awesome fork, thanks!
